name: openra
summary: Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: >
  Open Source real-time strategy game engine for early Westwood games
  such as Command & Conquer: Red Alert written in C# using SDL and
  OpenGL. Runs on Windows, Linux, *BSD and Mac OS X.
adopt-info: openra
grade: stable
confinement: strict
base: core18
compression: lzo

architectures:
- build-on: amd64
- build-on: i386
- build-on: armhf
- build-on: arm64
- build-on: ppc64el

layout:
  /usr/share/.mono:
    bind: $SNAP_COMMON/.mono

hooks:
  configure:
    plugs:
      - network

environment:
  MONO_CFG_DIR: $SNAP/etc
  MONO_CONFIG: $SNAP/etc/mono/config
  MONO_GAC_PREFIX: $SNAP/usr/lib/mono

apps:
  cnc:
    command: desktop-launch $SNAP/usr/local/bin/openra-cnc
    desktop: usr/local/share/applications/openra-cnc.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  d2k:
    command: desktop-launch $SNAP/usr/local/bin/openra-d2k
    desktop: usr/local/share/applications/openra-d2k.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  ra:
    command: desktop-launch $SNAP/usr/local/bin/openra-ra
    desktop: usr/local/share/applications/openra-ra.desktop
    plugs:
    - audio-playback
    - avahi-control
    - avahi-observe
    - desktop
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11

  # Not Available yet  
  # ts:
  #   command: desktop-launch $SNAP/usr/local/bin/openra-ts
  #   desktop: usr/local/share/applications/openra-ts.desktop
  #   plugs:
  #   - audio-playback
  #   - avahi-control
  #   - avahi-observe
  #   - desktop
  #   - mount-observe
  #   - network
  #   - network-bind
  #   - opengl
  #   - pulseaudio
  #   - removable-media
  #   - wayland
  #   - x11

parts:
  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
      - gnupg
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  mono:
    plugin: nil
    source: .
    override-pull: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
      apt update && apt -yqq upgrade

  openra:
    after: [desktop-glib-only, mono]
    plugin: make
    source: https://github.com/OpenRA/OpenRA/releases/download/release-$SNAPCRAFT_PROJECT_VERSION/OpenRA-release-$SNAPCRAFT_PROJECT_VERSION-source.tar.bz2
    #source: https://github.com/OpenRA/OpenRA.git
    override-pull: |
      if [ -f "$SNAPCRAFT_PROJECT_DIR"/build-type ]; then
        . "$SNAPCRAFT_PROJECT_DIR"/build-type
      else
        PLAYTEST=false
      fi
      curl -o api.txt https://api.github.com/repos/OpenRA/OpenRA/releases

      JQ_SCRIPT='[.[] | select(.prerelease == '"$PLAYTEST"')] | .[0]'
      VERSION=$(cat api.txt | jq "$JQ_SCRIPT"' | .tag_name')
      URL=$(cat api.txt | jq "$JQ_SCRIPT"' | .assets | map(select(.content_type == "application/x-bzip2")) | .[0] | .browser_download_url')

      curl -L "$(echo "$URL" | sed -e 's/"//g')" | tar jx

      sed -i 's|^Icon=\(.*\)$|Icon=/usr/local/share/icons/hicolor/128x128/apps/\1.png|;s|^Exec=|Exec=openra.{MOD}|' packaging/linux/openra.desktop.in
      sed -i 's@\({BIN_DIR}\|{GAME_INSTALL_DIR}\)@$SNAP/\1@g' packaging/linux/openra.in

      snapcraftctl set-version "$(echo "$VERSION" | sed -e 's/"//g')"
    override-build: |
      env TRAVIS=1 make dependencies
      env PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-shortcuts
    build-packages:
    - curl
    - jq
    - libfreetype6-dev
    - libglu1-mesa-dev
    - liblua5.1-0-dev
    - libopenal-dev
    - libsdl2-dev
    - mono-complete
    - nuget
    - unzip
    stage-packages:
    - ca-certificates-mono
    - libfreetype6
    - libglu1-mesa
    - liblua5.1-0
    - libopenal1
    - libsdl2-2.0-0
    - mono-complete
    - mount
    - wget
