name: Build Pull Requests

on:
- pull_request

jobs:
  snapcraft-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/arm/v7
        playtest:
        - 'true'
        - 'false'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Build
      id: build
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json > /dev/null
        sudo systemctl restart docker
        docker run --rm --tty --privileged \
          --volume "$GITHUB_WORKSPACE":"$GITHUB_WORKSPACE" \
          --workdir "$GITHUB_WORKSPACE" \
          --platform "${{ matrix.architecture }}" \
          diddledan/snapcraft:core18 env PLAYTEST="${{matrix.playtest}}" snapcraft

          SNAPFILE="$(find "$GITHUB_WORKSPACE" -maxdepth 1 -type f -name "*.snap" | head -n1)"
          sudo chown "$(id -u)":"$(id -g)" "$SNAPFILE"
          echo ::set-output name=snap::"$SNAPFILE"
    - name: Review
      uses: diddlesnaps/snapcraft-review-tools-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        isClassic: 'false'
