name: Check for new releases

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: get-latest-version
      run: |
        VERSION="$(curl https://api.github.com/repos/OpenRA/OpenRA/releases | jq '.[0] | .tag_name' | sed -e 's/"//g')"
        EDGEVER="$(snap info openra | awk '$1 == "edge:" { print $2 }')"
        BETAVER="$(snap info openra | awk '$1 == "beta:" { print $2 }')"

        if [ "$VERSION" != "$EDGEVER" ] && [ "$VERSION" != "$BETAVER" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build.stamp
        fi
    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Trigger build for new version
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
